---
title: "make_figures"
author: "Claire Morton"
date: "5/16/2024"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ipumsr)
library(srvyr)
library(tidysynthesis)
library(parsnip)
library("data.table")
library(recipes)
library(devtools)
load_all('../../syntheval')
library(syntheval)
library(dials)
library(tune)
library(gtools)
library(MASS)
library(caret)
library(gt)
library(ggpubr)
library(patchwork)

set.seed(78483)
```

## Functions for Figure 1, 2, S1, S2
```{r fig12s1s2_funcs}
make_specks_fig <- function(df, level_order, group_colors, type){
  #levels(as.factor(df$type))
  df$type <- as.factor(df$type)
  levels(df$type) <- c("LASSO", "Logistic Regression", "Random Forest", "Regression Tree")
  df$type <- as.character(df$type)
  if (type == "train"){
    ggplot(df, aes(x = "", 
                   group = type, 
                   color = type, 
                   y = as.numeric(specks_train)))+
      geom_boxplot()+
      ylab("SPECKS Value")+
      xlab("")+
      ggtitle("SPECKS")+
      scale_color_manual(values=group_colors)+
      labs(colour="Model Type")+
      theme_classic()+
      facet_wrap(facet = vars(factor(name, level = level_order)), nrow = 1)
  } else{
    ggplot(df, aes(x = "", 
                   group = type, 
                   color = type, 
                   y = as.numeric(specks_test)))+
      geom_boxplot()+
      ylab("SPECKS Value")+
      xlab("")+
      ggtitle("SPECKS")+
      scale_color_manual(values=group_colors)+
      labs(colour="Model Type")+
      theme_classic()+
      facet_wrap(facet = vars(factor(name, level = level_order)), nrow = 1)
  }
}

make_pmse_fig <- function(df, level_order, group_colors, type){
  #levels(as.factor(df$type))
  df$type <- as.factor(df$type)
  levels(df$type) <- c("LASSO", "Logistic Regression", "Random Forest", "Regression Tree")
  df$type <- as.character(df$type)
  if (type == "train"){
    ggplot(df, aes(x = "", 
                   group = type, 
                   color = type, 
                   y = as.numeric(pmse_train)))+
      geom_boxplot()+
      ylab("pMSE Value")+
      xlab("")+
      ggtitle("pMSE")+
      scale_color_manual(values=group_colors)+
      labs(colour="Model Type")+
      theme_classic()+
      facet_wrap(facet = vars(factor(name, level = level_order)), nrow = 1)
  } else{
    ggplot(df, aes(x = "", 
                   group = type, 
                   color = type, 
                   y = as.numeric(pmse_test)))+
      geom_boxplot()+
      ylab("pMSE Value")+
      xlab("")+
      ggtitle("pMSE")+
      scale_color_manual(values=group_colors)+
      labs(colour="Model Type")+
      theme_classic()+
      facet_wrap(facet = vars(factor(name, level = level_order)), nrow = 1)
  }
}

make_auc_fig <- function(df, level_order, group_colors, type){
  #levels(as.factor(df$type))
  df$type <- as.factor(df$type)
  levels(df$type) <- c("LASSO", "Logistic Regression", "Random Forest", "Regression Tree")
  df$type <- as.character(df$type)
  if (type == "train"){
    ggplot(df, aes(x = "", 
                   group = type, 
                   color = type, 
                   y = as.numeric(auc_train)))+
      geom_boxplot()+
      ylab("AUC Value")+
      xlab("")+
      ggtitle("AUC")+
      scale_color_manual(values=group_colors)+
      labs(colour="Model Type")+
      theme_classic()+
      facet_wrap(facet = vars(factor(name, level = level_order)), nrow = 1)
  } else{
    ggplot(df, aes(x = "", 
                   group = type, 
                   color = type, 
                   y = as.numeric(auc_test)))+
      geom_boxplot()+
      ylab("AUC Value")+
      xlab("")+
      ggtitle("AUC")+
      scale_color_manual(values=group_colors)+
      labs(colour="Model Type")+
      theme_classic()+
      facet_wrap(facet = vars(factor(name, level = level_order)), nrow = 1)
  }
}
```

## Figure S1
Uses output from model_comparison2.qmd (fig1_v2.csv) which has train/test for 10 models.
```{r figs1}
# indicates control (synthetic and confidential data from same distribution), errors with both mean and variance, 
# errors with correlations, and errors with means
df <- read.csv("fig1_v2.csv")
level_order <- c("Control", "Mean", "Correlation", "All") 
group_colors <- c("Logistic Regression" ="#361052", "Regression Tree" = "green", "LASSO" = "red", "Random Forest" = "blue")

fig_a = make_specks_fig(df, level_order, group_colors, type = "train")
fig_b = make_pmse_fig(df, level_order, group_colors, type = "train")
fig_c = make_auc_fig(df, level_order, group_colors, type = "train")

combined_plot <- (fig_a + theme(legend.position = "none")) /
                 (fig_b + theme(legend.position = "none")) /
                 (fig_c + theme(legend.position = "none")) +
                 plot_layout(guides = 'collect') &
                 theme(legend.position = "right")
ggsave("figures/fig_s1.pdf", plot = combined_plot, width = 7, height = 6)
ggsave("figures/fig_s1.png", plot = combined_plot, width = 7, height = 6)
```

```{r fig1}
fig_a = make_specks_fig(df, level_order, group_colors, type = "test")
fig_b = make_pmse_fig(df, level_order, group_colors, type = "test")
fig_c = make_auc_fig(df, level_order, group_colors, type = "test")

combined_plot <- (fig_a + theme(legend.position = "none")) /
                 (fig_b + theme(legend.position = "none")) /
                 (fig_c + theme(legend.position = "none")) +
                 plot_layout(guides = 'collect') &
                 theme(legend.position = "right")
ggsave("figures/fig_1.pdf", plot = combined_plot, width = 7, height = 6)
ggsave("figures/fig_1.png", plot = combined_plot, width = 7, height = 6)
```

```{r figs2}
df <- read.csv("fig2_v2.csv")
fig_a = make_specks_fig(df, level_order, group_colors, type = "train")
fig_b = make_pmse_fig(df, level_order, group_colors, type = "train")
fig_c = make_auc_fig(df, level_order, group_colors, type = "train")

combined_plot <- (fig_a + theme(legend.position = "none")) /
                 (fig_b + theme(legend.position = "none")) /
                 (fig_c + theme(legend.position = "none")) +
                 plot_layout(guides = 'collect') &
                 theme(legend.position = "right")
ggsave("figures/fig_s2.pdf", plot = combined_plot, width = 7, height = 6)
ggsave("figures/fig_s2.png", plot = combined_plot, width = 7, height = 6)
```

```{r fig2}
fig_a = make_specks_fig(df, level_order, group_colors, type = "test")
fig_b = make_pmse_fig(df, level_order, group_colors, type = "test")
fig_c = make_auc_fig(df, level_order, group_colors, type = "test")

combined_plot <- (fig_a + theme(legend.position = "none")) /
                 (fig_b + theme(legend.position = "none")) /
                 (fig_c + theme(legend.position = "none")) +
                 plot_layout(guides = 'collect') &
                 theme(legend.position = "right")
ggsave("figures/fig_2.pdf", plot = combined_plot, width = 7, height = 6)
ggsave("figures/fig_2.png", plot = combined_plot, width = 7, height = 6)
```

```{r fig3456_func}
make_fig3456 <- function(df, metric, group){
  
  if ((group == "pov") && (metric == "AUC")){
    df$synth_type = factor(df$synth_type, levels = c("nopov_bad", "nopov_med", "good", "pov_med", "pov_bad"))
    plot <- ggplot(df, aes(x = synth_type, y = aucs, color = pov_class))+
      geom_point(alpha = .5)+
      ylab("AUC")+
      xlab("Synthesis Type")+
      theme_classic()+
      scale_x_discrete(labels = c("Over-poor", "Over-fair", "Poverty-good", "Under-fair", "Under-poor"))+
      scale_color_discrete(name = "Group", labels = c("Over", "Under"))
  }
  if ((group == "pov") && (metric == "SPECKS")){
    df$synth_type = factor(df$synth_type, levels = c("nopov_bad", "nopov_med", "good", "pov_med", "pov_bad"))
    plot <- ggplot(df, aes(x = synth_type, y = speckss, color = pov_class))+
      geom_point(alpha = .5)+
      ylab("SPECKS")+
      xlab("Synthesis Type")+
      theme_classic()+
      scale_x_discrete(labels = c("Over-poor", "Over-fair", "Poverty-good", "Under-fair", "Under-poor"))+
      scale_color_discrete(name = "Group", labels = c("Over", "Under"))
  }
  if ((group == "race") && (metric == "AUC")){
    df$BLACK_class <- factor(df$BLACK_class, levels = c("noBLACK", "BLACK"))
    df$synth_type = factor(df$synth_type, levels = c("noBLACK_bad", "noBLACK_med", "good", "BLACK_med", "BLACK_bad"))
    plot <- ggplot(df, aes(x = synth_type, y = aucs, color = BLACK_class))+
      geom_point(alpha = .5)+
      ylab("AUC")+
      xlab("Synthesis Type")+
      theme_classic()+
      scale_x_discrete(labels = c("White-poor", "White-fair", "Race-good", "Black-fair", "Black-poor"))+
      scale_color_discrete(name = "Group", labels = c("White", "Black"))
  }
  if ((group == "race") && (metric == "SPECKS")){
    df$BLACK_class <- factor(df$BLACK_class, levels = c("noBLACK", "BLACK"))
    df$synth_type = factor(df$synth_type, levels = c("noBLACK_bad", "noBLACK_med", "good", "BLACK_med", "BLACK_bad"))
    plot <- ggplot(df, aes(x = synth_type, y = speckss, color = BLACK_class))+
      geom_point(alpha = .5)+
      ylab("SPECKS")+
      xlab("Synthesis Type")+
      theme_classic()+
      scale_x_discrete(labels = c("White-poor", "White-fair", "Race-good", "Black-fair", "Black-poor"))+
      scale_color_discrete(name = "Group", labels = c("White", "Black"))
  }
  return(plot)
}
```

```{r fig_35}
#Plot results
one_model_df <- read.csv("one_model_df_pov.csv")
two_model_df <- read.csv("two_model_df_pov.csv")

one_auc <- make_fig3456(one_model_df, metric = "AUC", group = "pov")
one_specks <- make_fig3456(one_model_df, metric = "SPECKS", group = "pov")
two_auc <- make_fig3456(two_model_df, metric = "AUC", group = "pov")
two_specks <- make_fig3456(two_model_df, metric = "SPECKS", group = "pov")

combined_plot <- (one_auc + theme(legend.position = "none")) /
                 (one_specks + theme(legend.position = "none")) +
                 plot_layout(guides = 'collect') &
                 theme(legend.position = "right")
ggsave("figures/fig_3.pdf", plot = combined_plot, width = 6, height = 6)
ggsave("figures/fig_3.png", plot = combined_plot, width = 6, height = 6)

combined_plot <- (two_auc + theme(legend.position = "none")) /
                 (two_specks + theme(legend.position = "none")) +
                 plot_layout(guides = 'collect') &
                 theme(legend.position = "right")
ggsave("figures/fig_5.pdf", plot = combined_plot, width = 6, height = 6)
ggsave("figures/fig_5.png", plot = combined_plot, width = 6, height = 6)
```

```{r fig_46}
#Plot results

one_model_df <- read.csv("one_model_df_black.csv")
two_model_df <- read.csv("two_model_df_black.csv")

one_auc <- make_fig3456(one_model_df, metric = "AUC", group = "race")
one_specks <- make_fig3456(one_model_df, metric = "SPECKS", group = "race")
two_auc <- make_fig3456(two_model_df, metric = "AUC", group = "race")
two_specks <- make_fig3456(two_model_df, metric = "SPECKS", group = "race")

combined_plot <- (one_auc + theme(legend.position = "none")) /
                 (one_specks + theme(legend.position = "none")) +
                 plot_layout(guides = 'collect') &
                 theme(legend.position = "right")
ggsave("figures/fig_4.pdf", plot = combined_plot, width = 6, height = 6)
ggsave("figures/fig_4.png", plot = combined_plot, width = 6, height = 6)

combined_plot <- (two_auc + theme(legend.position = "none")) /
                 (two_specks + theme(legend.position = "none")) +
                 plot_layout(guides = 'collect') &
                 theme(legend.position = "right")
ggsave("figures/fig_6.pdf", plot = combined_plot, width = 6, height = 6)
ggsave("figures/fig_6.png", plot = combined_plot, width = 6, height = 6)
```


Figures 7 and 8 are for the pMSE ratio
```{r fig7}
plot <- read.csv("pmse_ratio_pov.csv")

plot$synth_type = factor(plot$synth_type, levels = c("nopov_bad", "nopov_med", "good", "pov_med", "pov_bad"))

plot_pov <- ggplot(plot, aes(x = synth_type, group = pov_class, y = pmse, color = pov_class))+
  geom_point(alpha = .5)+
  #geom_pointrange(aes(ymin = lows, ymax = highs))+
  ylab("pMSE Ratio")+
  xlab("Synthesis Type")+
  theme_classic()+
  scale_x_discrete(labels = c("Over-poor", "Over-fair", "Poverty-good", "Under-fair", "Under-poor"))+
  scale_color_discrete(name = "Group", labels = c("Over", "Under"))

ggsave("figures/fig_7.pdf", plot = plot_pov, width = 6, height = 4)
ggsave("figures/fig_7.png", plot = plot_pov, width = 6, height = 4)
```

```{r fig8}

```

Graph results [FOR FIGURE 8]
```{r}
pmse_ratios = c(c(pmse_ratio_noBLACK_bad[[1]], pmse_ratio_noBLACK_bad[[2]]),
                c(pmse_ratio_noBLACK_med[[1]], pmse_ratio_noBLACK_med[[2]]),
                c(pmse_ratio_good[[1]], pmse_ratio_good[[2]]), 
                c(pmse_ratio_BLACK_med[[1]], pmse_ratio_BLACK_med[[2]]),
                c(pmse_ratio_BLACK_bad[[1]], pmse_ratio_BLACK_bad[[2]]))
                
synth_type = c("noBLACK_bad", "noBLACK_bad", "noBLACK_med", "noBLACK_med", "good", "good", "BLACK_med", "BLACK_med", "BLACK_bad", "BLACK_bad")
BLACK_class = c("noBLACK", "BLACK", "noBLACK", "BLACK", "noBLACK", "BLACK", "noBLACK", "BLACK", "noBLACK", "BLACK")
synth_type = factor(synth_type, levels = c("noBLACK_bad", "noBLACK_med", "good", "BLACK_med", "BLACK_bad"))

plot <- data.frame(pmse = pmse_ratios, synth_type = synth_type, BLACK_class = BLACK_class)
ggplot(plot, aes(x = synth_type, group = BLACK_class, y = pmse, color = BLACK_class))+
  geom_point()+
  #geom_pointrange(aes(ymin = lows, ymax = highs))+
  ylab("pMSE Ratio")+
  xlab("Synthesis Type")+
  theme_classic()
```









